version: '3.8'
services:
  # nginx:
  #   user: "1000:1000"
  #   image: nginx-tunestar:1.0
  #   volumes:
  #     - /battletube:/battletube
  #     - ./logs/nginx:/var/log/nginx
  #     - /mnt/videos:/mnt/videos
  #   ports:
  #     - "80:80"
  #     - "5000:5000"
  #     - "8888:8888"
  #     - "9999:9999"
  api:
    user: "1000:1000"
    image: fastapi-battletube:1.0
    ports:
      - "50000:8000"
    volumes:
      - ./apiContainer/fastApiOnairTest:/fastapi
      - ./logs:/fastapi/logs
      - /mnt/videos:/mnt/videos
      - /mnt/trash:/mnt/trash
    networks:
      default_bridge:
        ipv4_address: 172.26.0.30
  # redis-server
  redis:
    image: ems-redis:1.01
    ports:
      - "6379:6379"
    networks:
      default_bridge:
        ipv4_address: 172.26.0.40
  # encodingManagementService with ffmpeg
  ems:
    image: ems-ffmpeg:1.03
    user: "1000:1000"
    ports:
      - "15000:8000"
    volumes:
      - ./emsContainer/encodingManager:/ems
      - ./configs:/ems/configs
      - ./logs:/ems/logs
      - /mnt/videos:/mnt/videos
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    networks:
      default_bridge:
        ipv4_address: 172.26.0.50
networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
